# Generated by Django 5.1.3 on 2025-03-31 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=9)),
                ('price', models.PositiveSmallIntegerField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.stream')),
            ],
        ),
    ]
